# Generated by Django 4.0.3 on 2023-05-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0002_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
