# Generated by Django 4.0.3 on 2023-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0003_alter_visitors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
    ]
